services: 
 
 
  # Backend API
  backend:
    build:
      context: ./house-renting
      dockerfile: Dockerfile
    container_name: renthouse-backend
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "9024:8080"
    volumes:
      - ./house-renting/uploads:/app/uploads
    networks:
      - renthouse-network
    restart: unless-stopped

  # Frontend UI
  frontend:
    build:
      context: ./renthouse-ui
      dockerfile: Dockerfile
    container_name: renthouse-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:9024/api
    ports:
      - "9025:3000"
    depends_on:
      - backend
    networks:
      - renthouse-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  renthouse-network:
    driver: bridge 